config/routes.rb
Rails.application.routes.draw do
  
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root to: "messages#index"
  
  resources :messages, only: [:index, :create]

  mount ActionCable.server => '/cable'

  unless Rails.application.config.consider_all_requests_local
  	get '*path', to: 'errors#render_routing_error', via: :all
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dialect.rb
class Dialect < ActiveRecord::Base
	belongs_to :users, foreign_key: 'dialect_id'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user, :body

  def translate 
  	DegraeveHelper.call_api_method(user.dialect, body)
  end 

end

app/models/user.rb
class User < ApplicationRecord

  has_one  :dialect, primary_key: 'dialect_id', foreign_key: 'id'

  include Clearance::User
  enum status: [:offline, :online, :away]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery

  unless Rails.application.config.consider_all_requests_local
	rescue_from ActionController::RoutingError, with: :render_routing_error
  end 
  rescue_from ActiveRecord::RecordInvalid, with: :render_unprocessable_entity_response
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found_response

  
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
 def render_unprocessable_entity_response(exception)
    render json: exception.record.errors, status: :unprocessable_entity
  end

  def render_not_found_response(exception)
    render json: { error: exception.message }, status: :not_found
  end

  def render_routing_error
  	respond_to do |format|
  	  format.html { render template: 'errors/not_found', status: 404 }
  	  format.json { render json: { error: exception.message }, status: 404  }
      format.all { render nothing: true, status: 404 }
  	end
  end 
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_login
  
  def index
    @users = User.where(status: 1)
    @messages = Message.all
    @message = Message.new
  end

  def create
    @message = Message.new message_params
    if @message.save
      send_notifications
    else
      flash[:error] = "Could not send message"
      redirect_to messages_path
    end
  end

  private

  def message_params
    params.
      require(:message).
      permit(:body).
      merge(user: current_user)
  end

  def send_notifications
    ActionCable.server.broadcast "messages",
      message: @message.translate,
      user_email: current_user.email, 
      icon: current_user.dialect.icon_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  def create 
  	super
  	current_user.update_attribute("status", 1)
  end 
  def destroy 
  	current_user.update_attribute("status", 0)
  	super
  end 
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  private

  def user_params
    params[:user].permit(:email, :password, :dialect_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/degraeve_helper.rb
module DegraeveHelper 
  
  # Call an ADdegraeve translation API method
  #
  # @param dialect [Dialect]      contains URI and name for API endpoint
  # @param text    [String]       the string to translate
  def self.call_api_method(dialect, text)

    uri = URI.parse("#{dialect.path}?w=#{text}&d=#{dialect.name}")
    res = Net::HTTP.get(uri)
    
    @results = ActionController::Base.helpers.sanitize(res.split('<blockquote>')[1].split('</blockquote>')[0])
  end
end 

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "FoundationRailsSeries"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    .row
      - flash.each do |name, msg|
        - if msg.is_a?(String)
          = content_tag :div, msg, class: "alert-box #{name} radius"
    %div{:clas => "row"}
      = yield
    = javascript_include_tag "application"

app/views/messages/index.html.haml
%body
  .grid-frame
    #sidebar.medium-grid-block.collapse.medium-3.large-3.vertical{:position => "left", "zf-panel" => ""}
      .grid-content.collapse.shrink.hide-for-medium
        %a.secondary.button.expand{:href => "", "zf-close" => ""} Close
      .grid-content.collapse.shrink
        = image_tag("Dialect-Chat.png")
      .grid-content.collapse.shrink.avatar-section
        = image_tag(current_user.dialect.icon_path, size: "30x30")
        = current_user.email
    .grid-block.collapse.medium-9.large-9.vertical
      #header.shrink.collapse.grid-content
        %ul.menu-bar.primary
          %li.hide-for-medium
            %a{:href => "#", "zf-open" => "sidebar"} Menu
          %li
            = link_to "logout", sign_out_path, method: :delete
      .grid-block
        .grid-block.small-12.medium-9.vertical
          .grid-content.Messages
            - @messages.each do |message|
              %h4
                = image_tag(message.user.dialect.icon_path, size: "30x30")
                = message.user.email
              %p 
                = message.translate
              %hr/
          = form_for @message do |form|
            .message-input.grid-content.collapse.shrink
              %span.inline-label
                = form.text_field :body
                = form.submit "Send", data: { disable_with: false }, class: "button"
        .grid-content.medium-3.show-for-medium.message-side-bar
          %section.block-list
            %header Currently Active
            %ul.ActiveUsers
              - @users.each do |user|              
                %li
                  = user.email

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} ×

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="text-field">
  <%= form.label :dialect_id %>
  <%= collection_select(:user, :dialect_id, Dialect.all, :id, :name, prompt: true) %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div id="clearance" class="sign-up small-5 medium-5 vertical">
    <h2><%= t(".title") %></h2>

    <%= form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>

      <div class="submit-field">
        <%= form.submit %>
      </div>

      <div class="other-links">
        <%= link_to t(".sign_in"), sign_in_path %>
      </div>
    <% end %>
  </div>
</div>